# Welcome to Jekyll!
#
# This config file is for settings that affect the whole site.

# Site settings
locale: "en-US"
title: "Junteng Liu"
title_separator: "-"
subtitle:
name: "Junteng Liu"
description: "Personal homepage of Junteng Liu, a first-year PhD candidate at HKUST NLP Group."
url: "https://useveldafco.github.io"
baseurl: "/LJT-Homepage"
repository: "useveldafco/LJT-Homepage"
teaser:
logo:
masthead_title:
breadcrumbs: false
words_per_minute: 160
future: false

search: false
comments:
  provider: false
atom_feed:
  path:
analytics:
  provider: false

# Social sharing
twitter:
  username: "junteng88716710"

# Site author
author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group."
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "junteng88716710"

# Reading files
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
include:
  - .htaccess
  - _pages
exclude:
  - _drafts
  - _portfolio
  - _posts
  - _talks
  - _teaching
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      published: false
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
      published: true

# Publication categories
publication_category:
  preprints:
    title: "Preprints"
  conferences:
    title: "Conference Papers"

# HTML compression
compress_html:
  clippings: all
  ignore:
    envs: development
